from string import Template

keyfile = Template(
    """# Siglent ${model_id} Option Keys
### Device ID ${device_id}

## Installation
Keys can be installed via the device SCPI interface with the following commands:

Bandwidth keys: `MCBD <key>`
Option keys: `LCISL <key>`

Changes will be applied after a scope reboot.

## Keys
${key_table}
### Generated by ${package} ${version} on ${date}
"""
)
